/* ============================================
   MONE - Product Database
   ============================================ */

const PRODUCTS = [
  // WHISKY
  {
    id: 'whisky-001',
    name: 'Jack Daniels Old No.7',
    category: 'whisky',
    brand: 'Jack Daniels',
    description: 'Whisky Tennessee 1L',
    volume: '1L',
    price: 149.90,
    available: true,
    oldPrice: 179.90,
    badge: { type: 'off', value: 17 },
    tags: ['jack', 'jack daniels', 'tennessee'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Jack%20Daniels%20Old%20No.7/400/400',
  },
  {
    id: 'whisky-002',
    name: 'Jack Daniels Honey',
    category: 'whisky',
    brand: 'Jack Daniels',
    description: 'Whisky Tennessee Mel 1L',
    volume: '1L',
    price: 139.90,
    available: true,
    tags: ['jack', 'honey', 'jack honey'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Jack%20Daniels%20Honey/400/400',
  },
  {
    id: 'whisky-003',
    name: 'Red Label',
    category: 'whisky',
    brand: 'Johnnie Walker',
    description: 'Whisky Escoces 1L',
    volume: '1L',
    price: 119.90,
    available: true,
    tags: ['red', 'red label', 'johnnie'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Red%20Label/400/400',
  },
  {
    id: 'whisky-004',
    name: 'Black Label',
    category: 'whisky',
    brand: 'Johnnie Walker',
    description: 'Whisky Escoces 12 anos 1L',
    volume: '1L',
    price: 189.90,
    available: true,
    badge: { type: 'top' },
    tags: ['black', 'black label', 'johnnie'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Black%20Label/400/400',
  },
  {
    id: 'whisky-005',
    name: 'Chivas Regal 12',
    category: 'whisky',
    brand: 'Chivas',
    description: 'Whisky Escoces 12 anos 1L',
    volume: '1L',
    price: 179.90,
    available: true,
    tags: ['chivas', 'chivas 12'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Chivas%20Regal%2012/400/400',
  },
  {
    id: 'whisky-006',
    name: 'Ballantines',
    category: 'whisky',
    brand: 'Ballantines',
    description: 'Whisky Escoces 1L',
    volume: '1L',
    price: 89.90,
    available: true,
    tags: ['ballantines'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Ballantines/400/400',
  },
  {
    id: 'whisky-007',
    name: 'Jameson',
    category: 'whisky',
    brand: 'Jameson',
    description: 'Whisky Irlandes 1L',
    volume: '1L',
    price: 129.90,
    available: true,
    tags: ['jameson', 'irlandes'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Jameson/400/400',
  },
  {
    id: 'whisky-008',
    name: 'Wild Turkey 101',
    category: 'whisky',
    brand: 'Wild Turkey',
    description: 'Whisky Bourbon 1L',
    volume: '1L',
    price: 159.90,
    available: true,
    tags: ['wild turkey', 'turkey', 'bourbon'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Wild%20Turkey%20101/400/400',
  },

  // VODKA
  {
    id: 'vodka-001',
    name: 'Absolut',
    category: 'vodka',
    brand: 'Absolut',
    description: 'Vodka Sueca 1L',
    volume: '1L',
    price: 89.90,
    available: true,
    tags: ['absolut'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Absolut/400/400',
  },
  {
    id: 'vodka-002',
    name: 'Smirnoff',
    category: 'vodka',
    brand: 'Smirnoff',
    description: 'Vodka 1L',
    volume: '1L',
    price: 59.90,
    available: true,
    tags: ['smirnoff'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Smirnoff/400/400',
  },
  {
    id: 'vodka-003',
    name: 'Grey Goose',
    category: 'vodka',
    brand: 'Grey Goose',
    description: 'Vodka Premium 1L',
    volume: '1L',
    price: 199.90,
    available: true,
    badge: { type: 'top' },
    tags: ['grey goose', 'gray goose'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Grey%20Goose/400/400',
  },
  {
    id: 'vodka-004',
    name: 'Ciroc',
    category: 'vodka',
    brand: 'Ciroc',
    description: 'Vodca Uva 1L',
    volume: '1L',
    price: 159.90,
    available: true,
    tags: ['ciroc'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Ciroc/400/400',
  },

  // GIN
  {
    id: 'gin-001',
    name: 'Gordon\'s',
    category: 'gin',
    brand: 'Gordon\'s',
    description: 'Gin London Dry 1L',
    volume: '1L',
    price: 49.90,
    available: true,
    oldPrice: 59.90,
    badge: { type: 'off', value: 17 },
    tags: ['gordons', 'gordon'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Gordon%27s/400/400',
  },
  {
    id: 'gin-002',
    name: 'Tanqueray',
    category: 'gin',
    brand: 'Tanqueray',
    description: 'Gin London Dry 1L',
    volume: '1L',
    price: 99.90,
    available: true,
    tags: ['tanqueray'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Tanqueray/400/400',
  },
  {
    id: 'gin-003',
    name: 'Bombay Sapphire',
    category: 'gin',
    brand: 'Bombay',
    description: 'Gin Premium 1L',
    volume: '1L',
    price: 129.90,
    available: true,
    tags: ['bombay', 'sapphire'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Bombay%20Sapphire/400/400',
  },
  {
    id: 'gin-004',
    name: 'Beefeater',
    category: 'gin',
    brand: 'Beefeater',
    description: 'Gin London Dry 1L',
    volume: '1L',
    price: 69.90,
    available: true,
    tags: ['beefeater'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Beefeater/400/400',
  },

  // BALDES
  {
    id: 'cerveja-001',
    name: 'Heineken',
    category: 'baldes',
    brand: 'Heineken',
    description: 'Cerveja Puro Malte Lata 350ml',
    volume: '350ml',
    price: 6.90,
    available: true,
    oldPrice: 8.90,
    badge: { type: 'off', value: 22 },
    tags: ['heineken', 'hineken'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Heineken/400/400',
  },
  {
    id: 'cerveja-002',
    name: 'Heineken Long Neck',
    category: 'baldes',
    brand: 'Heineken',
    description: 'Cerveja Puro Malte 600ml',
    volume: '600ml',
    price: 9.90,
    available: true,
    tags: ['heineken', 'long neck'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Heineken%20Long%20Neck/400/400',
  },
  {
    id: 'cerveja-003',
    name: 'Skol Lata',
    category: 'baldes',
    brand: 'Skol',
    description: 'Cerveja Lata 350ml',
    volume: '350ml',
    price: 4.50,
    available: true,
    tags: ['skol'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Skol%20Lata/400/400',
  },
  {
    id: 'cerveja-004',
    name: 'Brahma Lata',
    category: 'baldes',
    brand: 'Brahma',
    description: 'Cerveja Lata 350ml',
    volume: '350ml',
    price: 4.50,
    available: true,
    tags: ['brahma'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Brahma%20Lata/400/400',
  },
  {
    id: 'cerveja-005',
    name: 'Amstel Lata',
    category: 'baldes',
    brand: 'Amstel',
    description: 'Cerveja Lata 350ml',
    volume: '350ml',
    price: 5.50,
    available: true,
    tags: ['amstel'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Amstel%20Lata/400/400',
  },
  {
    id: 'cerveja-006',
    name: 'Corona',
    category: 'baldes',
    brand: 'Corona',
    description: 'Cerveja Importada 355ml',
    volume: '355ml',
    price: 12.90,
    available: true,
    tags: ['corona'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Corona/400/400',
  },
  {
    id: 'cerveja-007',
    name: 'Stella Artois',
    category: 'baldes',
    brand: 'Stella Artois',
    description: 'Cerveja Puro Malte Long Neck 600ml',
    volume: '600ml',
    price: 10.90,
    available: true,
    tags: ['stella', 'artois'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Stella%20Artois/400/400',
  },
  {
    id: 'cerveja-008',
    name: 'Budweiser',
    category: 'baldes',
    brand: 'Budweiser',
    description: 'Cerveja Lata 350ml',
    volume: '350ml',
    price: 5.90,
    available: true,
    tags: ['bud', 'budweiser'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Budweiser/400/400',
  },

  // ENERGETICO
  {
    id: 'energetico-001',
    name: 'Red Bull',
    category: 'energetico',
    brand: 'Red Bull',
    description: 'Energetico Lata 250ml',
    volume: '250ml',
    price: 12.90,
    available: true,
    tags: ['red bull', 'energetico'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Red%20Bull/400/400',
  },
  {
    id: 'energetico-002',
    name: 'Monster Energy',
    category: 'energetico',
    brand: 'Monster',
    description: 'Energetico Lata 473ml',
    volume: '473ml',
    price: 14.90,
    available: true,
    tags: ['monster'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Monster%20Energy/400/400',
  },
  {
    id: 'energetico-003',
    name: 'Red Bull Sugar Free',
    category: 'energetico',
    brand: 'Red Bull',
    description: 'Energetico Zero Acucar 250ml',
    volume: '250ml',
    price: 12.90,
    available: true,
    tags: ['red bull', 'sugar free', 'zero'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Red%20Bull%20Sugar%20Free/400/400',
  },

  // GELO SABORIZADO
  {
    id: 'acessorios-001',
    name: 'Gelo 2kg',
    category: 'gelo',
    brand: 'Generic',
    description: 'Saco de Gelo 2kg',
    volume: '2kg',
    price: 8.90,
    available: true,
    tags: ['gelo'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Gelo%202kg/400/400',
  },
  {
    id: 'acessorios-002',
    name: 'Copo Caipirinha 300ml',
    category: 'copos',
    brand: 'Generic',
    description: 'Copo para whisky 300ml',
    volume: '300ml',
    price: 5.90,
    available: true,
    tags: ['copo', 'caipirinha', 'whisky'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Copo%20Caipirinha%20300ml/400/400',
  },
  {
    id: 'acessorios-003',
    name: 'Copo Long Drink',
    category: 'copos',
    brand: 'Generic',
    description: 'Copo Long Drink 400ml',
    volume: '400ml',
    price: 6.90,
    available: true,
    tags: ['copo', 'long drink'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Copo%20Long%20Drink/400/400',
  },
  {
    id: 'acessorios-004',
    name: 'Agua Mineral 500ml',
    category: 'garrafas',
    brand: 'Generic',
    description: 'Agua Mineral 500ml',
    volume: '500ml',
    price: 3.00,
    available: true,
    tags: ['agua', 'agua mineral'],
    inChat: true,
    imageUrl: 'https://picsum.photos/seed/Agua%20Mineral%20500ml/400/400',
  },

];

// Categories for filtering
const CATEGORIES = [
  { id: 'all', label: 'Todos' },
  { id: 'whisky', label: 'Whisky' },
  { id: 'vodka', label: 'Vodka' },
  { id: 'gin', label: 'Gin' },
  { id: 'ervas', label: 'Ervas de Tereré' },
  { id: 'copos', label: 'Copos' },
  { id: 'garrafas', label: 'Garrafas' },
  { id: 'baldes', label: 'Baldes' },
  { id: 'gelo', label: 'Gelo Saborizado' },
  { id: 'maromba', label: 'Mansão Maromba' },
  { id: 'energetico', label: 'Energéticos' }
];

// Store info
const STORE_INFO = {
  name: 'Money Adega & Tabacaria',
  slogan: 'Seu role comeca aqui.',
  hours: 'Seg a Sab: 09h as 23h | Dom: 10h as 22h',
  address: 'Rua Exemplo, 123 - Centro, Cuiaba - MT',
  phone: '(65) 99999-8888',
  whatsapp: '5565999998888',
  instagram: '@moneyadega',
  paymentMethods: 'PIX, Dinheiro, Cartao de Debito e Credito',
  deliveryFee: 5.00,
  minOrder: 30.00,
  avgTime: '45 min',
  neighborhoods: ['Centro', 'CPA', 'Alicerce', 'Alvorada', 'Morada do Ouro', 'Quilombo', 'Santa Rosa']
};

// Product helper functions
function getProductById(id) {
  return PRODUCTS.find(p => p.id === id);
}

function getProductsByCategory(category) {
  if (category === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === category);
}

function searchProducts(query) {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.tags.some(t => t.toLowerCase().includes(q)) ||
    p.category.toLowerCase().includes(q)
  );
}

function getProductIcon(category) {
  const icons = {
    whisky: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M18 8h1a4 4 0 0 1 0 8h-1"/><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/><path d="M6 1v3"/><path d="M10 1v3"/><path d="M14 1v3"/></svg>`,
    vodka: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M18 8h1a4 4 0 0 1 0 8h-1"/><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/><path d="M12 1v3"/></svg>`,
    gin: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z"/><path d="M12 2v20"/><path d="M2 12h20"/></svg>`,
    ervas: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/></svg>`,
    copos: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><path d="M3 6h18"/><path d="M16 10a4 4 0 0 1-8 0"/></svg>`,
    garrafas: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M12 22V10"/><path d="M12 10c-2 0-4-1.5-4-4V3h8v3c0 2.5-2 4-4 4z"/><path d="M8 3h8"/></svg>`,
    baldes: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M17 11h1a3 3 0 0 1 0 6h-1"/><path d="M9 12v6"/><path d="M13 12v6"/><path d="M5 7v2a3 3 0 0 0 3 3h2a3 3 0 0 0 3-3V7"/><path d="M5 7h10"/></svg>`,
    gelo: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M9 12h6"/><path d="M12 9v6"/></svg>`,
    maromba: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M6.5 6.5L17.5 17.5"/><path d="M17.5 6.5L6.5 17.5"/><circle cx="12" cy="12" r="10"/></svg>`,
    energetico: `<svg viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="1.5"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>`
  };
  return icons[category] || icons.whisky;
}
